### ISSUE TITLE
Increase visibility of the project on GitHub

### ISSUE THREAD

**Issue by DeveloppeurPascal** [Cooler2/ApusGameEngine#5]
Hi

Please add "delphi", "delphi-game-engine", "game-engine", "delphi-game" and "delphi-library" to the project topics on the repository.

I have some links outside GitHub to those ones and it should increase a little the visibility of this great project.

(and for games, "delphi" and "delphi-game" should be a good idea too)

Best regards

Patrick

**Comment by Cooler2** [comment]
Thank you! Added :-)

**Comment by abitrolly** [comment]
https://github.com/topics/delphi-game-engine tag is not very popular - only 2 titles including this one. It is better to replace it with tags "pascal" and "freepascal". And fix "gamdev" tag to be "gamedev".

**Comment by Cooler2** [comment]
Thanks, done! :)

**Comment by abitrolly** [comment]
148 stars for today. I don't know the growth rate, but should get over 160 at the end of the month. :D

**Comment by Cooler2** [comment]
Will see :-)
